version: '3'
services:
    api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 3000
        networks:
            - frontend
        deploy:
            replicas: 4
    nginx:
        restart: always
        image: nginx:latest
        ports:
            - 8080:80
        networks:
            - frontend
        depends_on:
            - api
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

networks:
    frontend:
        driver: bridge
