FROM node:20-slim
WORKDIR /app
COPY ./package*.json .
RUN npm ci
COPY . .
RUN npm build

FROM node:20-slim
RUN useradd -ms /bin/bash api
USER api
COPY --from=0 /app/dist/index.js /index.js
CMD node index.js